### ISSUE TITLE
Bilan par acteur

### ISSUE THREAD

**Issue by bdlarzac** [bdlarzac/chantiers#2]
Ajouter un nouveau type de bilan, le bilan par acteur, qui permet de voir toutes les activités d'un acteur entre deux dates.

**Comment by bdlarzac** [comment]
Le code est en bonne partie déjà écrit, la méthode acteur.GetActivitesByDate() peut être réutilise, en lui ajoutant des paramètres date1 et date2.

**Comment by tig12** [comment]
Issue fermée car incluse dans la v2
