### ISSUE TITLE
Configuration pour déploiement serverless

### ISSUE THREAD

**Issue by flibustenet** [bdlarzac/chantiers#7]
Placer la plupart de la configuration en base (copie du fichier yml dans une table config dans un premier temps). Le reste en variable d'environnement (connexion à la base).

- [x] Connexion à la base sur une seule variable (soit `postgresql://user:pass@host` soit `dbname=... user=...`)
- [x] Configuration sur variables d'environnement
- [ ] Table config et écran de saisie
- [ ] Tester sur Scalingo
- [ ] Revoir le principe de sauvegarde

**Comment by flibustenet** [comment]
sql.DB est un pool de connection et non pas une connection unique. A chaque Exec il prend une connection dans le pool, rien ne garanti que ce sera la même et donc que le search_path aura été appelé...
Actuellement ça ne semble pas gênant car il prend toujours la même vu qu'il n'y a pas foule et que le serveur PG est local, mais ça reste aléatoire.
Solution : indiquer le schema dans la chaîne de connection pg. (je le fait)
Autre solution : utiliser des transactions.
edit: pour la même raison un Ping ne sert à rien

**Comment by tig12** [comment]
Opérationnel depuis plusieurs mois
